In [1]:
import numpy as np

In [5]:
# create array
# 메소드와 멤버: dtype, ndim, shape, size
arr = np.arange(15)
print(arr, type(arr))

list_a = list(range(15))
print(list_a, type(list_a))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] <class 'numpy.ndarray'>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14] <class 'list'>


In [8]:
arr = np.arange(15).reshape(3,5)
print(arr, type(arr))
print('배열의 차원 : ', arr.ndim)
print('배열의 (행,열) : ', arr.shape)
print('배열의 size : ', arr.size)
print('배열의 각 요소의 데이터 타입 : ', arr.dtype, arr.dtype.name, arr.dtype.itemsize)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] <class 'numpy.ndarray'>
배열의 차원 :  2
배열의 (행,열) :  (3, 5)
배열의 size :  15
배열의 각 요소의 데이터 타입 :  int32 int32 4


In [18]:
# list로 배열 생성
a1 = np.array([1.0, 2.0, 3.0])
print(a1, type(a1), a1.ndim, a1.shape, a1.dtype)
print()
a2 = np.array([[1.0, 2.0, 3.0], [1.0, 2.0, 3.0]])
print(a2, type(a2), a2.ndim, a2.shape, a2.dtype)
print()

[1. 2. 3.] <class 'numpy.ndarray'> 1 (3,) float64

[[1. 2. 3.]
 [1. 2. 3.]] <class 'numpy.ndarray'> 2 (2, 3) float64



In [29]:
a = np.zeros(5)
b = np.zeros((2, 3))
print(b)
print()
c = np.zeros((5, 2), dtype="i")
print(c, c.dtype)
print()
d = np.zeros(5, dtype="U4")
print(d, d.dtype)
print()
e = np.ones((2, 3, 4), dtype="i8")
print(e, e.dtype)
print()
f = np.ones_like(b, dtype="f")
print(f, f.dtype)
print()
g = np.empty((4, 3))
print(g, g.dtype)
print()

[[0. 0. 0.]
 [0. 0. 0.]]

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]] int32

['' '' '' '' ''] <U4

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]] int64

[[1. 1. 1.]
 [1. 1. 1.]] float32

[[9.89505955e-312 2.47032823e-322 0.00000000e+000]
 [0.00000000e+000 1.89146896e-307 1.04082753e-047]
 [6.25884973e-091 1.16345884e+165 8.31435566e-072]
 [3.69553448e-033 3.99910963e+252 2.25286340e+184]] float64



In [32]:
x1 = np.array([1.0, 2.0, 3.0])
y1 = np.array([5.0, 10.0, 15.0])
x2 = np.array([[1.0, 2.0], [3.0, 4.0]])
y2 = np.array([[5.0, 10.0], [15.0, 20.0]])
z1 = np.array([-1.0, -2.0])
z2 = np.array([[5.0], [10.0], [15.0]])

In [40]:
# array 기본 연산
print(x1 + y1)     # [ 6. 12. 18.]
print(x1 - y1)     # [ -4.  -8. -12.]
print(x1 * y1)     # [ 5. 20. 45.]
print(x1 / y1)     # [0.2 0.2 0.2]
print(x2 + y2)     # [[ 6. 12.]
                   #  [18. 24.]]

# 행과 열의 갯수가 다른 경우 : broadcast
print(x2 + z1)
print(x2 * z1)
print(x1 ** 2)
print(x1 >= 2)

[ 6. 12. 18.]
[ -4.  -8. -12.]
[ 5. 20. 45.]
[0.2 0.2 0.2]
[[ 6. 12.]
 [18. 24.]]
[[0. 0.]
 [2. 2.]]
[[-1. -4.]
 [-3. -8.]]
[1. 4. 9.]
[False  True  True]


In [52]:
# shape 변경 -> 1차원으로 평탄화
print(x2)
print(x2.flatten())
x3 = x2.reshape(x2.size)
print(x3.shape)
print(x3.reshape((2,2)))

[[1. 2.]
 [3. 4.]]
[1. 2. 3. 4.]
(4,)
[[1. 2.]
 [3. 4.]]


In [53]:
x2.reshape(-1,)

array([1., 2., 3., 4.])

In [58]:
a = np.arange(10) ** 2
print(a)
print(a[2])
print(a[3:5])
a[0:6:2] = -a[0:6:2]
print(a[::-1])
for i in a:
    print(i + 1)

[ 0  1  4  9 16 25 36 49 64 81]
4
[ 9 16]
[ 81  64  49  36  25 -16   9  -4   1   0]
1
2
-3
10
-15
26
37
50
65
82


In [61]:
a = np.arange(1,21,1).reshape(4,5)
print(a)
print(a[2,3])
print(a[0:4,1])
print(a[1,])
print(a[-1,])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
14
[ 2  7 12 17]
[ 6  7  8  9 10]
[16 17 18 19 20]


In [73]:
a=np.arange(6)
print(a)
print(np.sin(a))
print(np.cos(a))
print(np.tanh(a))
print(np.exp(a))

[0 1 2 3 4 5]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[0.         0.76159416 0.96402758 0.99505475 0.9993293  0.9999092 ]
[  1.           2.71828183   7.3890561   20.08553692  54.59815003
 148.4131591 ]


In [244]:
a = np.arange(0.01, 1, 0.05)
print(np.log(a))
a1 = np.array([2,3,4])
a2 = np.array([1,5,2])
print(np.maximum(a1,a2))
print(np.minimum(a1,a2))
print(np.sum(a1))
print(np.random.choice(100, 5))
print(np.random.choice(5, 3, p=[0.1, 0, 0.3, 0.6, 0]))    # p의 값은 모두 더하면 1
print(np.random.rand(2,3))
print(np.random.randn(2,3))
print(np.random.randint(10))

[-4.60517019 -2.81341072 -2.20727491 -1.83258146 -1.56064775 -1.34707365
 -1.17118298 -1.02165125 -0.89159812 -0.77652879 -0.67334455 -0.5798185
 -0.49429632 -0.41551544 -0.34249031 -0.27443685 -0.21072103 -0.15082289
 -0.09431068 -0.04082199]
[2 5 4]
[1 3 2]
9
[82 53 32 64 12]
[2 2 2]
[[0.23360705 0.27759677 0.2094996 ]
 [0.32132004 0.87814538 0.4615363 ]]
[[ 1.2811603   0.71938527 -2.12516368]
 [ 0.71796237 -0.01655682  0.86347126]]
9


In [251]:
a = np.array([6,2,3,1,4,5])
print(a)
print(np.argmax(a), a[np.argmax(a)])
print(np.argmin(a))

[6 2 3 1 4 5]
0 6
3


In [258]:
a = np.array([[0.1,0.8,0.2],[0.3,0.2,0.5],[0.9,0.5,0.3]])
print(a)
print(np.argmax(a))
print(np.argmax(a, axis=0))
print(np.argmax(a, axis=1))

[[0.1 0.8 0.2]
 [0.3 0.2 0.5]
 [0.9 0.5 0.3]]
6
[2 0 1]
[1 2 0]


In [259]:
# 기술 통계 함수
x = np.array([18, 5, 10, 23, 19, -8, 10, 0, 0, 5, 2, 15, 8, 2, 5, 4, 15, -1, 4, -7, -24, 7, 9, -6, 23, -13])

In [260]:
print(len(x))
print('평균 -> ', np.mean(x))
print('분산 -> ', np.var(x))
print('표준편차 -> ', np.std(x))
print('최대값 -> ', np.max(x))
print('최소값 -> ', np.min(x))
print('중앙값 -> ', np.median(x))
print('사분위수 -> ', np.percentile(x, 25))
print('사분위수 -> ', np.percentile(x, 75))

26
평균 ->  4.8076923076923075
분산 ->  115.23224852071006
표준편차 ->  10.734628476137871
최대값 ->  23
최소값 ->  -24
중앙값 ->  5.0
사분위수 ->  0.0
사분위수 ->  10.0


In [264]:
np.random.seed(0)
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [266]:
x = np.arange(10)

In [268]:
np.random.shuffle(x)
x

array([0, 2, 6, 3, 9, 8, 5, 4, 1, 7])

In [273]:
np.random.choice(x, x.size, replace=False)

array([2, 6, 0, 4, 7, 5, 1, 3, 9, 8])

In [274]:
# 샘플링 : choice 함수 사용
np.random.choice(5, 5, replace=False)
np.random.choice(5, 3, replace=False)
np.random.choice(5, 10)
np.random.choice(5, 10, p = [0.1, 0, 0.2, 0.7,0])

array([3, 3, 3, 0, 3, 0, 3, 3, 3, 3])

In [277]:
np.random.randint(10, size=10)
np.random.randint(10, 20, size=10)
np.random.randint(10, 20, size=(3,5))

array([[16, 15, 13, 11, 18],
       [10, 14, 19, 16, 15],
       [17, 18, 18, 19, 12]])

In [280]:
x = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [298]:
x1 = (x % 3) == 0
x11 = x[x1]
print(x11)

[ 3  6  9 12 15 18]


In [299]:
x2 = (x % 4) == 1
x22 = x[x2]
print(x22)

[ 1  5  9 13 17]


In [302]:
x3 = x1 & x2
x33 = x[x3]
print(x33)

[9]
